## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

theme = "hugo-story"
baseURL = "https://gallois.cc"
languageCode = "en-us"
title = "Benjamin Gallois"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
# googleAnalytics = "your-google-analytics-id"


## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "Benjamin Gallois Webpage"
  logo = "images/banner.jpg"
  favicon = true

[Params.social]
  github = "https://github.com/bgallois/"
  email = "benjamin@gallois.cc"
  linkedin = "https://www.linkedin.com/in/benjamin-gallois-554800187/"
  cv = "downloads/bg_cv.pdf"
  pgp = "downloads/pgp_public.txt"
  lib = "https://library.gallois.cc/"
